# 项目端口以及tomcat服务器编码
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: novel-api
  # 激活配置文件
  profiles:
    active: dev
#swagger 开关
swagger2:
  enable: true
#logging配置
logging:
  file: ${logging.path}/${spring.application.name}.log
  path: logs
  level:
    com.study: debug
jwt:
  # 请求头
  header: Authorization
  #盐值
  secret: mySecret
  # 过期时间
  expiration: 14400000
  # 认定方式
  tokenHead: Bearer
  #加入以下配置 对应生成 mapper.xml 的路径
mybatis-plus:
  type-aliases-package: com.example.novel.domain
  mapper-locations: classpath:com.example.novel.mapper/*.xml



